import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';
import { Document, Packer, Paragraph, TextRun } from 'docx';
import * as XLSX from 'xlsx';
import PptxGenJS from 'pptxgenjs';

const clean=(v:unknown)=>String(v??'').trim().replace(/\/$/,'');
const pid=()=>clean(process.env.VITE_FIREBASE_PROJECT_ID||process.env.FIREBASE_PROJECT_ID);
const db=()=>clean(process.env.VITE_FIREBASE_DATABASE_ID||process.env.FIREBASE_DATABASE_ID)||'(default)';
const bucket=()=>clean(process.env.VITE_FIREBASE_STORAGE_BUCKET||process.env.FIREBASE_STORAGE_BUCKET);
export const jsonResponse=(res:any,status:number,body:unknown)=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body));};
export function encryptBridgeToken(payload:Record<string,unknown>,secret:string){const key=createHash('sha256').update(secret).digest(),iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv);const body=Buffer.concat([c.update(JSON.stringify(payload),'utf8'),c.final()]);return Buffer.concat([iv,c.getAuthTag(),body]).toString('base64url');}
export function decryptBridgeToken(token:string,secret:string){try{const r=Buffer.from(token,'base64url');if(r.length<29)return null;const d=createDecipheriv('aes-256-gcm',createHash('sha256').update(secret).digest(),r.subarray(0,12));d.setAuthTag(r.subarray(12,28));return JSON.parse(Buffer.concat([d.update(r.subarray(28)),d.final()]).toString('utf8')) as Record<string,unknown>;}catch{return null;}}
async function firestore(path:string,token:string,init?:RequestInit){const p=pid();if(!p)throw new Error('FIREBASE_PROJECT_ID_NOT_CONFIGURED');const r=await fetch(`https://firestore.googleapis.com/v1/projects/${encodeURIComponent(p)}/databases/${encodeURIComponent(db())}/documents/${path}`,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(init?.headers||{})}});const t=await r.text();let b:any;try{b=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(`FIRESTORE_${r.status}: ${b?.error?.message||t||r.statusText}`);return b;}
const from=(v:any):any=>{if(!v)return null;if('stringValue'in v)return v.stringValue;if('integerValue'in v)return Number(v.integerValue);if('doubleValue'in v)return v.doubleValue;if('booleanValue'in v)return v.booleanValue;if('timestampValue'in v)return v.timestampValue;if('nullValue'in v)return null;if('arrayValue'in v)return(v.arrayValue?.values||[]).map(from);if('mapValue'in v)return Object.fromEntries(Object.entries(v.mapValue?.fields||{}).map(([k,x])=>[k,from(x)]));return null;};
const to=(v:any):any=>{if(v==null)return{nullValue:null};if(typeof v==='string')return{stringValue:v};if(typeof v==='boolean')return{booleanValue:v};if(typeof v==='number'&&Number.isInteger(v))return{integerValue:String(v)};if(typeof v==='number')return{doubleValue:v};if(Array.isArray(v))return{arrayValue:{values:v.map(to)}};if(typeof v==='object')return{mapValue:{fields:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,to(x)]))}};return{stringValue:String(v)};};
export async function getProject(projectId:string,token:string){const d=await firestore(`documents/documents/${encodeURIComponent(projectId)}`,token);return Object.fromEntries(Object.entries(d.fields||{}).map(([k,v])=>[k,from(v)]));}
export async function patchProject(projectId:string,token:string,fields:Record<string,any>){const p=pid();if(!p)throw new Error('FIREBASE_PROJECT_ID_NOT_CONFIGURED');const mask=Object.keys(fields).map(k=>`updateMask.fieldPaths=${encodeURIComponent(k)}`).join('&');const r=await fetch(`https://firestore.googleapis.com/v1/projects/${encodeURIComponent(p)}/databases/${encodeURIComponent(db())}/documents/documents/${encodeURIComponent(projectId)}?${mask}`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({fields:Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,to(v)]))})});if(!r.ok)throw new Error(`FIRESTORE_PATCH_${r.status}: ${await r.text()}`);}
function lines(c:any):string[]{if(c==null)return[];if(typeof c==='string')return c.replace(/<[^>]+>/g,'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(Array.isArray(c))return c.flatMap(lines);if(typeof c==='object')return Object.entries(c).flatMap(([k,v])=>[`${k}: ${typeof v==='object'?JSON.stringify(v):String(v)}`]);return[String(c)];}
export async function buildOfficeFile(project:any,kind:'word'|'excel'|'powerpoint'){const title=String(project.title||'Orbit'),l=lines(project.content??project.details??project.summary??project.previewSnippet);if(kind==='word'){const d=new Document({sections:[{children:[new Paragraph({children:[new TextRun({text:title,bold:true,size:32})]}),...l.map(x=>new Paragraph(x))]}]});return{buffer:Buffer.from(await Packer.toBuffer(d)),mime:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',ext:'docx'};}if(kind==='excel'){const wb=XLSX.utils.book_new(),ws=XLSX.utils.aoa_to_sheet([['Orbit',title],...(l.length?l.map(x=>[x]):[['']])]);XLSX.utils.book_append_sheet(wb,ws,'Orbit');return{buffer:Buffer.from(XLSX.write(wb,{type:'buffer',bookType:'xlsx'})),mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',ext:'xlsx'};}const ppt=new PptxGenJS();ppt.layout='LAYOUT_WIDE';const s=ppt.addSlide();s.addText(title,{x:.7,y:.7,w:11.2,h:.7,fontSize:28,bold:true});if(l.length)s.addText(l.join('\n'),{x:.9,y:1.7,w:10.8,h:4.7,fontSize:16,valign:'top'});return{buffer:Buffer.from(await ppt.write({outputType:'nodebuffer'}) as Buffer),mime:'application/vnd.openxmlformats-officedocument.presentationml.presentation',ext:'pptx'};}
export async function uploadOfficeFile(path:string,buffer:Buffer,mime:string,token:string){const b=bucket();if(!b)throw new Error('FIREBASE_STORAGE_BUCKET_NOT_CONFIGURED');const r=await fetch(`https://storage.googleapis.com/upload/storage/v1/b/${encodeURIComponent(b)}/o?uploadType=media&name=${encodeURIComponent(path)}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':mime,'Content-Length':String(buffer.length)},body:buffer});if(!r.ok)throw new Error(`STORAGE_UPLOAD_${r.status}: ${await r.text()}`);const t=randomBytes(24).toString('hex'),op=encodeURIComponent(path);const m=await fetch(`https://firebasestorage.googleapis.com/v0/b/${encodeURIComponent(b)}/o/${op}`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({metadata:{firebaseStorageDownloadTokens:t}})});if(!m.ok)throw new Error(`STORAGE_METADATA_${m.status}: ${await m.text()}`);return`https://firebasestorage.googleapis.com/v0/b/${encodeURIComponent(b)}/o/${op}?alt=media&token=${encodeURIComponent(t)}`;}
