import React, { useState } from 'react';
import { IconChevronLeft, IconChevronRight, IconSparkles } from '@tabler/icons-react';
export interface CopilotShellProps { children: React.ReactNode; title: string; contextTitle?: string; contextItems?: Array<{ id: string; label: string; detail?: string }>; onContextSelect?: (id: string) => void; }
export const CopilotShell: React.FC<CopilotShellProps> = ({ children, title, contextTitle = 'Contexto', contextItems = [], onContextSelect }) => {
 const [rightOpen,setRightOpen]=useState(true);
 return <section className="orbit-copilot-shell h-full min-h-0 flex overflow-hidden bg-white dark:bg-[#111318] border border-slate-200 dark:border-slate-800">
  <div className="min-w-0 flex-1 flex flex-col"><div className="h-12 shrink-0 border-b border-slate-200 dark:border-slate-800 flex items-center px-3 gap-2"><IconSparkles className="h-4 w-4 text-violet-600"/><span className="text-xs font-black">{title}</span><span className="ml-auto text-[9px] font-bold text-emerald-600 dark:text-emerald-400">IA gratuita</span></div><div className="min-h-0 flex-1">{children}</div></div>
  <aside className={`hidden xl:flex shrink-0 flex-col border-l border-slate-200 dark:border-slate-800 bg-slate-50/60 dark:bg-[#0d0f13] transition-[width] duration-200 ${rightOpen?'w-[250px]':'w-[44px]'}`}>
   <div className="h-12 px-2 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between">{rightOpen?<span className="text-xs font-black">{contextTitle}</span>:null}<button type="button" onClick={()=>setRightOpen(v=>!v)} className="h-8 w-8 rounded-lg hover:bg-slate-200/70 dark:hover:bg-slate-800 flex items-center justify-center" aria-label={rightOpen?'Recolher contexto':'Expandir contexto'}>{rightOpen?<IconChevronRight className="h-4 w-4"/>:<IconChevronLeft className="h-4 w-4"/>}</button></div>
   {rightOpen?<div className="p-2 space-y-1 overflow-y-auto">{contextItems.length?contextItems.map(item=><button key={item.id} type="button" onClick={()=>onContextSelect?.(item.id)} className="w-full text-left rounded-lg p-2.5 hover:bg-white dark:hover:bg-slate-900"><div className="text-[11px] font-bold truncate">{item.label}</div>{item.detail?<div className="mt-0.5 text-[9px] text-slate-500 line-clamp-2">{item.detail}</div>:null}</button>):<div className="p-3 text-[10px] text-slate-500">Abra um arquivo ou selecione um contexto para trabalhar com o Nexus AI.</div>}</div>:null}
  </aside>
 </section>;
};